### ISSUE TITLE
Retrouver la liste des catégories

### ISSUE THREAD

**Issue by Franck106** [Franck106/Team-A-Front#26]
on a perdu la liste des catégorie
![image](https://user-images.githubusercontent.com/54889417/91336849-d7ecf300-e7d2-11ea-92a6-9edf90bda704.png)

**Comment by pckerneis** [comment]
J'ai tout pullé sur les branches master mais je ne reproduis pas le bug...

**Comment by Franck106** [comment]
ok je ferme l'issue alors
